Parameters:
    ClonName:
      Description: Instagram Clone
      Type: String

Resources:

    LoadBalancerSecurityGroup:
        Type: AWS::EC2::SecurityGroup
        Properties:
          GroupDescription: Allow http access to our load LoadBalancer
          VpcId:
            Fn::ImportValue:
              VPCID
          SecurityGroupIngress:
            - IpProtocol: tcp
              FromPort: 80
              ToPort: 80
              CidrIp: 0.0.0.0/0

    WebServerSecurityGroup:
        Type: AWS::EC2::SecurityGroup
        Properties:
          GroupDescription: Allow http access to our hosts from the LB Security Group
          VpcId:
            Fn::ImportValue:
                VPCID
          SecurityGroupIngress:
            - IpProtocol: tcp
              FromPort: 80
              ToPort: 80
              SourceSecurityGroupId: !Ref LoadBalancerSecurityGroup
              
    WebAppLaunchTemplate:
      Type: AWS::EC2::LaunchTemplate
      Properties: 
        LaunchTemplateName: Web-server
        LaunchTemplateData:
          UserData:
            Fn::Base64: !Sub |
              #!/bin/bash
              sudo apt-get update -y
              sudo apt-get install nginx -y
              sudo service nginx start

              aws s3 cp s3://${StaticContentBucket}/index.html /usr/share/nginx/html/index.html
              
          ImageId: ami-0bd01199a9dd76709
          SecurityGroupIds:
            - !Ref WebServerSecurityGroup
          InstanceType: t2.micro
          BlockDeviceMappings:
          - DeviceName: "/dev/sdk"
            Ebs:
              VolumeSize: '10'
          IamInstanceProfile:
            Name: !Ref WebAppInstanceProfile

    WebAppInstanceRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: Web-server
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: 'Allow'
            Principal:
              Service:
              - 'ec2.amazonaws.com'
            Action:
            - 'sts:AssumeRole'
        Policies:
          - PolicyName: s3
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
              - Effect: Allow
                Action:
                - 's3:GetObject'
                - 's3:PutObject'
                - 's3:DeleteObject'
                Resource:
                  - !Sub "${StaticContentBucket.Arn}/*"
         
              - Effect: Allow
                Action: 
                - 's3:ListBucket'
                Resource:
                  - !GetAtt StaticContentBucket.Arn
                  
    WebAppInstanceProfile:
      Type: AWS::IAM::InstanceProfile
      Properties:
        Path: '/'
        Roles:
        - !Ref WebAppInstanceRole

    WebAppGroup:
      Type: AWS::AutoScaling::AutoScalingGroup
      Properties:
        VPCZoneIdentifier: 
        - Fn::ImportValue: 
           private-subnets
        LaunchTemplate:
          LaunchTemplateId: !Ref WebAppLaunchTemplate
          Version: !GetAtt WebAppLaunchTemplate.LatestVersionNumber
        MinSize: '1'
        DesiredCapacity: '1'
        MaxSize: '4'
        TargetGroupARNs:
          - Ref: WebAppTargetGroup

    WebAppLB:
      Type: AWS::ElasticLoadBalancingV2::LoadBalancer
      Properties:
        Subnets:
          - Fn::ImportValue: public-subnet1
          - Fn::ImportValue: public-subnet2
        SecurityGroups:
          - Ref: LoadBalancerSecurityGroup
        Scheme: internet-facing

    Listener:
      Type: AWS::ElasticLoadBalancingV2::Listener
      Properties:
        DefaultActions:
          - Type: forward
            TargetGroupArn:
              Ref: WebAppTargetGroup
        LoadBalancerArn:
          Ref: WebAppLB
        Port: 80
        Protocol: HTTP

    ALBListenerRule:
      Type: AWS::ElasticLoadBalancingV2::ListenerRule
      Properties:
        Actions:
          - Type: forward
            TargetGroupArn: !Ref WebAppTargetGroup
        Conditions:
         - Field: path-pattern
           Values: [/]
        ListenerArn: !Ref Listener
        Priority: 1

    WebAppTargetGroup:
      Type: AWS::ElasticLoadBalancingV2::TargetGroup
      Properties:
        HealthCheckIntervalSeconds: 10
        HealthCheckProtocol: HTTP
        HealthCheckPath: /
        HealthCheckTimeoutSeconds: 8
        HealthyThresholdCount: 2
        UnhealthyThresholdCount: 5
        Port: 80
        Protocol: HTTP
        VpcId:
          Fn::ImportValue:
             VPCID

    StaticContentBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: !Sub "${AWS::StackName}-static-content"
        PublicAccessBlockConfiguration:
          BlockPublicAcls: true
          BlockPublicPolicy: false
          IgnorePublicAcls: true
          RestrictPublicBuckets: false
        WebsiteConfiguration:
          IndexDocument: index.html


    StaticContentBucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket: !Ref StaticContentBucket
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Sid: PublicReadGetObject
              Effect: Allow
              Principal: "*"
              Action: "s3:GetObject"
              Resource: !Sub "${StaticContentBucket.Arn}/*"

Outputs:
  LoadBalancerURL:
    Description: Public URL of the Application Load Balancer
    Value: !Sub http://${WebAppLB.DNSName}
    Export:
      Name: LoadBalancerURL
